import type { Metadata } from "next";
import "@/public/styles/app.css";

import { Toaster } from "sonner";
import { BaseProvider } from "@/lib/providers/base";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon:'/images/favicon.ico'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body>
        <BaseProvider>
          {children}
          <Toaster />
        </BaseProvider>
      </body>
    </html>
  );
}
